export const EVENTS = {
	WRITING_EMAIL_NEWSLETTER_FORM: 'WRITING EMAIL NEWSLETTER FORM',
	SUBMIT_NEWSLETTER_FORM: 'SUBMIT NEWSLETTER FORM',
	EMAIL_ME: 'EMAIL ME',
	CLICK_ON_SOCIAL_ICON: 'CLICK ON SOCIAL ICON',
	PRONOUNCE_MY_NAME: 'PRONOUNCE MY NAME',
	TRIGGER_COLOR_MODE: 'TRIGGER COLOR MODE',
	SEARCH_ARTICLES: 'SEARCH ARTICLES',
	ENLARGE_IMAGE: 'ENLARGE IMAGE',
	SWITCH_LANG: 'SWITCH_LANG',
};

export const EVENTS_CATEGORIES = {
	HIGH: 'high',
	MID: 'medium',
	LOW: 'low',
};
