export const EVENTS = {
	WRITING_EMAIL_NEWSLETTER_FORM: 'WRITING_EMAIL_NEWSLETTER_FORM',
	SUBMIT_NEWSLETTER_FORM: 'SUBMIT_NEWSLETTER_FORM',
	EMAIL_ME: 'EMAIL_ME',
	CLICK_ON_SOCIAL_ICON: 'CLICK_ON_SOCIAL_ICON',
	PRONOUNCE_MY_NAME: 'PRONOUNCE_MY_NAME',
	TRIGGER_COLOR_MODE: 'TRIGGER_COLOR_MODE',
	SEARCH_ARTICLES: 'SEARCH_ARTICLES',
	ENLARGE_IMAGE: 'ENLARGE_IMAGE',
};

export const EVENTS_CATEGORIES = {
	HIGH: 'high',
	MID: 'medium',
	LOW: 'low',
};
